apiVersion: "v1"
kind: "Service"
metadata:
  name: "face-result-web-service"
  labels:
    app: "face-result-web"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "face-result-web"
  type: "LoadBalancer"
  loadBalancerIP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: face-result-web
  name: face-result-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-result-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: face-result-web
    spec:
      containers:
      - image: supakornbabe/spai-face-result-web:dev-7dd69e6
        name: spai-face-result-web
        resources: {}
